# Site settings
title: Eugene Cheung | Developer + Designer
email: ey.cheung@outlook.com
description: "A passionate developer with an eye for beautiful creations."
baseurl: ""
url: "http://echeung.me"
twitter_username: arkon
github_username:  arkon

# Build settings
markdown: kramdown
permalink: pretty
